name: Docker Compose Build & Deploy

on:
  push:
    branches:
      - main  # Change this to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on any command failure

            cd /home/ubuntu/docker/tropitech
            git pull
            cd /home/ubuntu/docker
            echo "🛠️ Building new Docker images..."
            docker-compose build --no-cache
            echo "✅ Build successful! Restarting containers..."
            docker-compose down
            docker-compose up -d
